### PR TITLE
Fix custom tool example

### PR DESCRIPTION
**Pull request by dillonalaird**

### CODE REVIEW

**Review by yungyuantseng — COMMENTED** [review]
Thanks for the correction.
I also notice that there is no requirements.txt under examples/custom_tools.
I'm not sure that this will cause the problems or not.
Appreciate your efforts!

**Comment by dillonalaird** [comment]
> Thanks for the correction. I also notice that there is no requirements.txt under examples/custom_tools. I'm not sure that this will cause the problems or not. Appreciate your efforts!

Good catch, thanks! Just added

**Review by yungyuantseng — APPROVED** [review]
It's look good to me now!
I'll try this version, if I meet any problems, I'll report you!
Thank you so much.

**Review by shankar-vision-eng — APPROVED** [review]
LGTM

**Pull request merged**
